# Generated by Django 6.0.4 on 2026-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_report_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
