# Generated by Django 6.0.4 on 2026-04-17 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_problemtype_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_path', models.CharField(max_length=500, verbose_name='Путь к бэкапу')),
                ('backup_type', models.CharField(choices=[('database', 'База данных'), ('files', 'Файлы'), ('full', 'Полный')], max_length=20, verbose_name='Тип бэкапа')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('in_progress', 'В процессе')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Лог бэкапа',
                'verbose_name_plural': 'Логи бэкапов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='SMTP сервер')),
                ('email_port', models.IntegerField(default=587, verbose_name='Порт')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Использовать TLS')),
                ('email_host_user', models.EmailField(max_length=254, verbose_name='Логин email')),
                ('email_host_password', models.CharField(max_length=100, verbose_name='Пароль приложения')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки email',
                'verbose_name_plural': 'Настройки email',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='reports_photos/', verbose_name='Фото проблемы'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название чек-листа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='monitor.section', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Шаблон чек-листа',
                'verbose_name_plural': 'Шаблоны чек-листов',
                'ordering': ['section__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пункта')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='monitor.checklisttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Пункты чек-листов',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DailyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('green', 'Выполнен'), ('yellow', 'Частично выполнен'), ('red', 'Не выполнен')], default='red', max_length=10, verbose_name='Статус')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.section', verbose_name='Участок')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.checklisttemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ежедневный чек-лист',
                'verbose_name_plural': 'Ежедневные чек-листы',
                'ordering': ['-date', 'section__name'],
                'unique_together': {('user', 'template', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.checklistitem', verbose_name='Пункт')),
                ('daily_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitor.dailychecklist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Результат пункта',
                'verbose_name_plural': 'Результаты пунктов',
                'unique_together': {('daily_checklist', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('equipment', 'Оборудование'), ('checklist', 'Чек-лист')], max_length=20, verbose_name='Тип')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.checklisttemplate', verbose_name='Чек-лист')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.equipment', verbose_name='Оборудование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'unique_together': {('user', 'content_type', 'equipment', 'checklist_template')},
            },
        ),
    ]
